source src/iruleuri.tcl
source src/assert.tcl

namespace import ::testcl::*
namespace import ::testcl::URI::*

# Comment out to suppress logging
#log::lvSuppressLE info 0

#test encoding
assertStringEquals "abcxyz" [encode abcxyz]
assertStringEquals "ABCXYZ" [encode ABCXYZ]
assertStringEquals "0189" [encode 0189]

assertStringEquals "%20" [encode " "]
assertStringEquals "%21" [encode "!"]
assertStringEquals "%22" [encode "\""]
assertStringEquals "%23" [encode "#"]
assertStringEquals "%24" [encode "$"]
assertStringEquals "%25" [encode "%"]
assertStringEquals "%26" [encode "&"]
assertStringEquals "%27" [encode "'"]
assertStringEquals "%28" [encode "("]
assertStringEquals "%29" [encode ")"]
assertStringEquals "%2a" [encode "*"]
assertStringEquals "%2b" [encode "+"]
assertStringEquals "%2c" [encode ","]
assertStringEquals "-" [encode "-"]
assertStringEquals "." [encode "."]
assertStringEquals "%2f" [encode "/"]
assertStringEquals "%3a" [encode ":"]
assertStringEquals "%3b" [encode ";"]
assertStringEquals "%3c" [encode "<"]
assertStringEquals "%3d" [encode "="]
assertStringEquals "%3e" [encode ">"]
assertStringEquals "%3f" [encode "?"]
assertStringEquals "%40" [encode "@"]
assertStringEquals "%5b" [encode "\["]
assertStringEquals "%5c" [encode "\\"]
assertStringEquals "%5d" [encode "\]"]
assertStringEquals "%5e" [encode "^"]
assertStringEquals "_" [encode "_"]
assertStringEquals "%60" [encode "`"]
assertStringEquals "%7b" [encode "{"]
assertStringEquals "%7c" [encode "|"]
assertStringEquals "%7d" [encode "}"]
assertStringEquals "~" [encode "~"]

assertStringEquals " " [decode "%20"]
assertStringEquals "!" [decode "%21"]
assertStringEquals "\"" [decode "%22"]
assertStringEquals "#" [decode "%23"]
assertStringEquals "\$" [decode "%24"]
assertStringEquals "%" [decode "%25"]
assertStringEquals "&" [decode "%26"]
assertStringEquals "'" [decode "%27"]
assertStringEquals "(" [decode "%28"]
assertStringEquals ")" [decode "%29"]
assertStringEquals "*" [decode "%2A"]
assertStringEquals "*" [decode "%2a"]
assertStringEquals "+" [decode "%2B"]
assertStringEquals "+" [decode "%2b"]
assertStringEquals "," [decode "%2C"]
assertStringEquals "," [decode "%2c"]
assertStringEquals "-" [decode "%2D"]
assertStringEquals "-" [decode "%2d"]
assertStringEquals "." [decode "%2E"]
assertStringEquals "." [decode "%2e"]
assertStringEquals "/" [decode "%2F"]
assertStringEquals "/" [decode "%2f"]
assertStringEquals "0" [decode "%30"]
assertStringEquals "1" [decode "%31"]
assertStringEquals "2" [decode "%32"]
assertStringEquals "3" [decode "%33"]
assertStringEquals "4" [decode "%34"]
assertStringEquals "5" [decode "%35"]
assertStringEquals "6" [decode "%36"]
assertStringEquals "7" [decode "%37"]
assertStringEquals "8" [decode "%38"]
assertStringEquals "9" [decode "%39"]
assertStringEquals ":" [decode "%3A"]
assertStringEquals ":" [decode "%3a"]
assertStringEquals ";" [decode "%3B"]
assertStringEquals ";" [decode "%3b"]
assertStringEquals "<" [decode "%3C"]
assertStringEquals "<" [decode "%3c"]
assertStringEquals "=" [decode "%3D"]
assertStringEquals "=" [decode "%3d"]
assertStringEquals ">" [decode "%3E"]
assertStringEquals ">" [decode "%3e"]
assertStringEquals "?" [decode "%3F"]
assertStringEquals "?" [decode "%3f"]
assertStringEquals "@" [decode "%40"]
assertStringEquals "A" [decode "%41"]
assertStringEquals "B" [decode "%42"]
assertStringEquals "C" [decode "%43"]
assertStringEquals "D" [decode "%44"]
assertStringEquals "E" [decode "%45"]
assertStringEquals "F" [decode "%46"]
assertStringEquals "G" [decode "%47"]
assertStringEquals "H" [decode "%48"]
assertStringEquals "I" [decode "%49"]
assertStringEquals "J" [decode "%4A"]
assertStringEquals "J" [decode "%4a"]
assertStringEquals "K" [decode "%4B"]
assertStringEquals "K" [decode "%4b"]
assertStringEquals "L" [decode "%4C"]
assertStringEquals "L" [decode "%4c"]
assertStringEquals "M" [decode "%4D"]
assertStringEquals "M" [decode "%4d"]
assertStringEquals "N" [decode "%4E"]
assertStringEquals "N" [decode "%4e"]
assertStringEquals "O" [decode "%4F"]
assertStringEquals "O" [decode "%4f"]
assertStringEquals "P" [decode "%50"]
assertStringEquals "Q" [decode "%51"]
assertStringEquals "R" [decode "%52"]
assertStringEquals "S" [decode "%53"]
assertStringEquals "T" [decode "%54"]
assertStringEquals "U" [decode "%55"]
assertStringEquals "V" [decode "%56"]
assertStringEquals "W" [decode "%57"]
assertStringEquals "X" [decode "%58"]
assertStringEquals "Y" [decode "%59"]
assertStringEquals "Z" [decode "%5A"]
assertStringEquals "Z" [decode "%5a"]
assertStringEquals "\[" [decode "%5B"]
assertStringEquals "\[" [decode "%5b"]
assertStringEquals "\\" [decode "%5C"]
assertStringEquals "\\" [decode "%5c"]
assertStringEquals "\]" [decode "%5D"]
assertStringEquals "\]" [decode "%5d"]
assertStringEquals "^" [decode "%5E"]
assertStringEquals "^" [decode "%5e"]
assertStringEquals "_" [decode "%5F"]
assertStringEquals "_" [decode "%5f"]
assertStringEquals "`" [decode "%60"]
assertStringEquals "a" [decode "%61"]
assertStringEquals "b" [decode "%62"]
assertStringEquals "c" [decode "%63"]
assertStringEquals "d" [decode "%64"]
assertStringEquals "e" [decode "%65"]
assertStringEquals "f" [decode "%66"]
assertStringEquals "g" [decode "%67"]
assertStringEquals "h" [decode "%68"]
assertStringEquals "i" [decode "%69"]
assertStringEquals "j" [decode "%6A"]
assertStringEquals "j" [decode "%6a"]
assertStringEquals "k" [decode "%6B"]
assertStringEquals "k" [decode "%6b"]
assertStringEquals "l" [decode "%6C"]
assertStringEquals "l" [decode "%6c"]
assertStringEquals "m" [decode "%6D"]
assertStringEquals "m" [decode "%6d"]
assertStringEquals "n" [decode "%6E"]
assertStringEquals "n" [decode "%6e"]
assertStringEquals "o" [decode "%6F"]
assertStringEquals "o" [decode "%6f"]
assertStringEquals "p" [decode "%70"]
assertStringEquals "q" [decode "%71"]
assertStringEquals "r" [decode "%72"]
assertStringEquals "s" [decode "%73"]
assertStringEquals "t" [decode "%74"]
assertStringEquals "u" [decode "%75"]
assertStringEquals "v" [decode "%76"]
assertStringEquals "w" [decode "%77"]
assertStringEquals "x" [decode "%78"]
assertStringEquals "y" [decode "%79"]
assertStringEquals "z" [decode "%7A"]
assertStringEquals "z" [decode "%7a"]
assertStringEquals "\{" [decode "%7B"]
assertStringEquals "\{" [decode "%7b"]
assertStringEquals "|" [decode "%7C"]
assertStringEquals "|" [decode "%7c"]
assertStringEquals "\}" [decode "%7D"]
assertStringEquals "\}" [decode "%7d"]
assertStringEquals "~" [decode "%7E"]
assertStringEquals "~" [decode "%7e"]

assertStringEquals "parameter=my URL encoded parameter value with metacharacters (&*@#\[\])" [decode "parameter=my%20URL%20encoded%20parameter%20value%20with%20metacharacters%20(%26*%40%23%5b%5d)"]

assertStringEquals "testcl.com" [host "http://testcl.com/test"]
assertStringEquals "www.google.com" [host "https://www.google.com:443"]

assertStringEquals "index.jsp" [basename "/main/index.jsp?user=test&login=check"]

assertStringEquals "80" [port "http://testcl.com/test"]
assertStringEquals "8889" [port "https://testcl.com:8889/test"]
assertStringEquals "0" [port "file://testcl.com/test"]

assertStringEquals "http" [protocol "http://testcl.com"]
assertStringEquals "https" [protocol "https://testcl.com"]
assertStringEquals "ftp" [protocol "ftp://testcl.com"]
assertStringEquals "" [protocol "/test"]

assertStringEquals "value2" [query "/path/to/file.ext?param1=value1&param2=value2" "param2"]
assertStringEquals "" [query "/path/to/file.ext?param1=value1&param2=value2" "param3"]

assertStringEquals "/path/to/" [path "/path/to/file.ext?param=value"]
assertStringEquals "2" [path "/path/to/file.ext?param=value" depth]
assertStringEquals "/path/to/" [path "/path/to/file.ext?param=value" 1]
assertStringEquals "/to/" [path "/path/to/file.ext?param=value" 2]
assertStringEquals "/to/some/" [path "/path/to/some/crazy/file.ext?param=value" 2 3]

# This is probably a bug
# assertStringEquals "1" [compare "http://testcl.com" "http://testcl.com/"]
assertStringEquals "1" [compare "http://TesTcl.com/" "http://testcl.com/"]
assertStringEquals "1" [compare "http://TesTcl.com/" "HTTP://testcl.com/"]


