# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

if  {[namespace exists ::testcl]} {
  #already loaded
  return
} else {

  # Verify jtcl-irule extension
  if { [catch { expr {"abc" starts_with "a"} } errormsg ] } {
    puts stderr "WARNING"	  
    puts stderr "WARNING It seems like the jtcl-irule extension isn't properly loaded"
    puts stderr "WARNING None of the custom iRule operator extensions to Tcl will work"
    puts stderr "WARNING Please check your JTcl classpath - see TesTcl documentation"
    puts stderr "WARNING"		  
  }
		
}

package ifneeded testcl 1.0.2 [list source [file join $dir src/assert.tcl]]\n[list source [file join $dir src/it.tcl]]\n[list source [file join $dir src/on.tcl]]\n[list source [file join $dir src/onirule.tcl]]\n[list source [file join $dir src/irulehttp.tcl]]

# Disable certain Tcl commands from iRules
source [file join $dir src/disabled_commands.tcl]
